export interface CatalogElement {
  category: string;
  name: string;
  lifespan: number;
  lifespanLabel: string;
  constructionTypes: string[];
  defectTypes: string[];
}

const commonDefects = ["No defect observed", "Other defect"];

export const catalog: CatalogElement[] = [
  { category: "External Envelope", name: "Roof", lifespan: 60, lifespanLabel: "50-70 years", constructionTypes: ["Pitched concrete tile", "Pitched natural slate", "Pitched fibre cement slate", "Flat felt or bitumen", "Flat GRP", "Flat EPDM", "Other"], defectTypes: [...commonDefects, "Slipped or missing tiles", "Cracked tiles", "Defective flashing", "Membrane failure", "Structural deflection", "Water ingress", "Moss growth"] },
  { category: "External Envelope", name: "Chimneys", lifespan: 65, lifespanLabel: "60+ years", constructionTypes: ["Brick with concrete cap", "Brick without cap", "Rendered stack", "Precast stack", "Not applicable", "Other"], defectTypes: [...commonDefects, "Pointing deteriorated", "Cap defective", "Flaunching cracked", "Structural movement", "Flashing defective", "Damp penetration"] },
  { category: "External Envelope", name: "Brickwork", lifespan: 70, lifespanLabel: "40-100 years", constructionTypes: ["Facing brick cavity wall", "Facing brick solid wall", "Engineering brick", "Rendered blockwork", "Stone masonry", "Other"], defectTypes: [...commonDefects, "Mortar joints eroded", "Spalling bricks", "Hairline cracking", "Structural cracking", "Efflorescence", "Damp penetration", "Bulging"] },
  { category: "External Envelope", name: "Render", lifespan: 30, lifespanLabel: "20-40 years", constructionTypes: ["Sand cement render", "Silicone render", "Pebble dash", "Monocouche", "Lime render", "External wall insulation", "Other"], defectTypes: [...commonDefects, "Hairline cracking", "Significant cracking", "Delamination", "Biological growth", "Staining", "Water ingress"] },
  { category: "External Envelope", name: "Cladding", lifespan: 25, lifespanLabel: "20-30 years", constructionTypes: ["Timber", "Composite board", "Fibre cement", "Profiled steel", "Aluminium cassette", "Brick slip", "Other"], defectTypes: [...commonDefects, "Damaged panels", "Loose fixings", "Fading", "Sealant deterioration", "Structural damage", "Moisture ingress"] },
  { category: "External Envelope", name: "Windows", lifespan: 28, lifespanLabel: "20-35 years", constructionTypes: ["uPVC double glazed", "uPVC single glazed", "Aluminium double glazed", "Timber double glazed", "Timber single glazed", "Steel glazed", "Other"], defectTypes: [...commonDefects, "Failed sealed unit", "Frame deterioration", "Cracked glass", "Ironmongery defective", "Draught", "Restrictor missing", "Sealant deterioration"] },
  { category: "External Envelope", name: "External Doors", lifespan: 30, lifespanLabel: "25-35 years", constructionTypes: ["uPVC panelled", "uPVC glazed", "Composite panelled", "Timber solid", "Aluminium glazed", "Steel security", "Other"], defectTypes: [...commonDefects, "Frame deterioration", "Poor fit", "Ironmongery defective", "Weather seals defective", "Security defective", "Threshold damaged"] },
  { category: "External Envelope", name: "Gutters", lifespan: 25, lifespanLabel: "20-30 years", constructionTypes: ["uPVC half round", "uPVC ogee", "Cast iron", "Aluminium", "Zinc", "Other"], defectTypes: [...commonDefects, "Blocked", "Leaking joint", "Sagging", "Cracked section", "Missing section", "Poor discharge"] },
  { category: "External Envelope", name: "Downpipes", lifespan: 25, lifespanLabel: "20-30 years", constructionTypes: ["uPVC circular", "uPVC square", "Cast iron", "Aluminium", "Zinc", "Other"], defectTypes: [...commonDefects, "Blocked", "Leaking joint", "Cracked section", "Missing section", "Poor discharge"] },
  { category: "Internal Areas", name: "Walls", lifespan: 7, lifespanLabel: "5-10 years", constructionTypes: ["Painted plaster", "Painted plasterboard", "Ceramic tile", "Wallpaper", "Timber panelling", "Other"], defectTypes: [...commonDefects, "Cracking", "Damp or mould", "Water staining", "Loose plaster", "Decoration deterioration", "Impact damage"] },
  { category: "Internal Areas", name: "Ceilings", lifespan: 7, lifespanLabel: "5-10 years", constructionTypes: ["Painted plaster", "Painted plasterboard", "Textured finish", "Suspended tile", "Timber boarded", "Other"], defectTypes: [...commonDefects, "Cracking", "Damp staining", "Mould", "Loose plaster", "Sagging", "Impact damage"] },
  { category: "Internal Areas", name: "Floors", lifespan: 12, lifespanLabel: "10-15 years", constructionTypes: ["Carpet", "Vinyl", "LVT", "Ceramic tile", "Timber", "Laminate", "Concrete", "Other"], defectTypes: [...commonDefects, "Worn covering", "Trip hazard", "Loose covering", "Structural bounce", "Subfloor defect", "Damp ingress"] },
  { category: "Internal Areas", name: "Internal Doors", lifespan: 32, lifespanLabel: "25-40 years", constructionTypes: ["Hollow core", "Solid core", "FD30 fire door", "FD60 fire door", "Timber panelled", "Glazed panel", "Other"], defectTypes: [...commonDefects, "Poor fit", "Ironmongery defective", "Frame damaged", "Closer missing", "Fire seals missing", "Rating label missing"] },
  { category: "Internal Areas", name: "Decorations", lifespan: 7, lifespanLabel: "5-10 years", constructionTypes: ["Matt emulsion", "Silk emulsion", "Eggshell", "Gloss", "Wallpaper", "Wood stain", "Other"], defectTypes: [...commonDefects, "Peeling paint", "Staining", "Mould", "Wallpaper lifting", "Surface damage", "Discolouration"] },
  { category: "Kitchen", name: "Kitchen Units", lifespan: 20, lifespanLabel: "20 years", constructionTypes: ["Laminate standard", "Laminate premium", "Painted timber", "High gloss", "Shaker", "Vinyl wrapped", "Other"], defectTypes: [...commonDefects, "Door damaged", "Carcass damaged", "Drawer defective", "Hinge defective", "Kickboard missing", "Unit loose"] },
  { category: "Kitchen", name: "Worktops", lifespan: 20, lifespanLabel: "20 years", constructionTypes: ["Laminate", "Solid timber", "Composite", "Granite", "Quartz", "Ceramic", "Other"], defectTypes: [...commonDefects, "Chipped", "Delaminating", "Burn damage", "Water damage", "Edge trim loose"] },
  { category: "Kitchen", name: "Sink", lifespan: 25, lifespanLabel: "20-30 years", constructionTypes: ["Stainless steel", "Ceramic", "Composite granite", "Other"], defectTypes: [...commonDefects, "Blocked waste", "Leaking trap", "Tap defective", "Staining", "Cracked", "Sealant deteriorated"] },
  { category: "Kitchen", name: "Appliances", lifespan: 12, lifespanLabel: "10-15 years", constructionTypes: ["Electric hob", "Induction hob", "Gas hob", "Electric oven", "Gas oven", "Integrated appliance", "None provided", "Other"], defectTypes: [...commonDefects, "Not functioning", "Damaged", "Missing", "Gas safety concern", "Electrical safety concern", "End of life"] },
  { category: "Kitchen", name: "Flooring", lifespan: 12, lifespanLabel: "10-15 years", constructionTypes: ["Vinyl", "LVT", "Ceramic tile", "Porcelain tile", "Carpet", "Timber", "Laminate", "Other"], defectTypes: [...commonDefects, "Worn", "Lifting edges", "Grout deterioration", "Cracked tiles", "Loose tiles"] },
  { category: "Kitchen", name: "Wall Finishes", lifespan: 25, lifespanLabel: "20-30 years", constructionTypes: ["Ceramic tile", "Porcelain tile", "Painted plaster", "Glass splashback", "Stainless splashback", "Other"], defectTypes: [...commonDefects, "Grout deterioration", "Cracked tiles", "Loose tiles", "Missing tiles", "Mould", "Sealant deterioration"] },
  { category: "Bathroom", name: "Bath / Shower", lifespan: 30, lifespanLabel: "30 years", constructionTypes: ["Panel bath", "Steel bath", "Walk-in shower", "Wet room", "Shower tray", "Other"], defectTypes: [...commonDefects, "Sealant deterioration", "Bath or tray cracked", "Screen leaking", "Taps defective", "Trap leaking", "Valve defective"] },
  { category: "Bathroom", name: "WC", lifespan: 25, lifespanLabel: "20-30 years", constructionTypes: ["Close coupled", "Back to wall", "Wall hung", "Other"], defectTypes: [...commonDefects, "Cistern not filling", "Cistern leaking", "Pan cracked", "Seat defective", "Flush defective"] },
  { category: "Bathroom", name: "Wash Hand Basin", lifespan: 25, lifespanLabel: "20-30 years", constructionTypes: ["Pedestal", "Wall mounted", "Semi-recessed", "Vanity unit", "Corner basin", "Other"], defectTypes: [...commonDefects, "Tap defective", "Trap leaking", "Sealant deteriorated", "Basin cracked", "Basin loose", "Overflow blocked"] },
  { category: "Bathroom", name: "Floor Finishes", lifespan: 12, lifespanLabel: "10-15 years", constructionTypes: ["Ceramic tile", "Porcelain tile", "Vinyl", "Safety vinyl", "Other"], defectTypes: [...commonDefects, "Worn", "Grout deterioration", "Cracked tiles", "Lifting edges", "Slip hazard"] },
  { category: "Bathroom", name: "Extract Ventilation", lifespan: 12, lifespanLabel: "10-15 years", constructionTypes: ["Humidistat fan", "Timer fan", "Pull cord fan", "PIV", "MVHR", "None present", "Other"], defectTypes: [...commonDefects, "Fan inoperative", "Fan noisy", "Fan absent", "Low extract rate", "Ducting disconnected", "Grille blocked"] },
  { category: "Building Services", name: "Heating", lifespan: 13, lifespanLabel: "12-15 years", constructionTypes: ["Gas combi boiler", "Gas system boiler", "Electric storage", "Electric panel", "Air source heat pump", "Ground source heat pump", "District heating", "Other"], defectTypes: [...commonDefects, "No heat", "Boiler inefficient", "Radiator not heating", "Pipework leaking", "Controls defective", "Safety certificate missing"] },
  { category: "Building Services", name: "Hot Water", lifespan: 25, lifespanLabel: "20-30 years", constructionTypes: ["Combi instantaneous", "Unvented cylinder", "Vented cylinder", "Immersion heater", "Heat pump", "Solar thermal", "Other"], defectTypes: [...commonDefects, "Insufficient hot water", "No hot water", "Cylinder leaking", "Thermostat defective", "Expansion vessel defective", "Relief valve defective"] },
  { category: "Building Services", name: "Electrical Installation", lifespan: 35, lifespanLabel: "25-40 years", constructionTypes: ["Rewirable fuse board", "MCB and RCD", "RCBO", "AFDD", "Single phase", "Three phase", "Other"], defectTypes: [...commonDefects, "EICR overdue", "Old consumer unit", "Accessories defective", "Wiring deteriorated", "Bonding defective", "RCD defective", "Circuits overloaded"] },
  { category: "Building Services", name: "Lighting", lifespan: 17, lifespanLabel: "15-20 years", constructionTypes: ["LED recessed", "LED surface", "LED batten", "Pendant", "Fluorescent", "Smart control", "Other"], defectTypes: [...commonDefects, "Luminaire not working", "Fitting damaged", "Provision inadequate", "Flex defective", "Switch defective"] },
  { category: "Building Services", name: "Fire Alarm", lifespan: 12, lifespanLabel: "10-15 years", constructionTypes: ["L2 addressable", "L2 conventional", "LD1 interlinked", "LD2 interlinked", "LD3 single point", "Heat alarm", "None present", "Other"], defectTypes: [...commonDefects, "Panel fault", "Detector missing", "Detector defective", "Battery flat", "System absent", "Service overdue", "Sounder defective"] },
  { category: "Building Services", name: "Emergency Lighting", lifespan: 12, lifespanLabel: "10-15 years", constructionTypes: ["Central battery", "Self-contained maintained", "Self-contained non-maintained", "Escape sign", "None present", "Other"], defectTypes: [...commonDefects, "Test failure", "Battery defective", "System absent", "Records overdue", "Luminaire defective"] },
  { category: "Building Services", name: "Mechanical Ventilation", lifespan: 25, lifespanLabel: "20-30 years", constructionTypes: ["Central MVHR", "Decentralised MVHR", "Central MEV", "PIV", "Natural ventilation", "Other"], defectTypes: [...commonDefects, "System inoperative", "Filters overdue", "Ducting defective", "Poor airflow", "Heat exchanger defective", "Controls defective"] }
];

export const categories = [...new Set(catalog.map((item) => item.category))];
export const conditionOptions = [
  { value: "A", label: "A - Good", description: "Sound condition with no significant defects" },
  { value: "B", label: "B - Satisfactory", description: "Serviceable with early signs of wear" },
  { value: "C", label: "C - Poor", description: "Deteriorating and requires planned action" },
  { value: "D", label: "D - Failed", description: "End of life or a health and safety risk" }
] as const;
export const priorityOptions = [
  { value: "1", label: "1 - Urgent", description: "Immediate action required" },
  { value: "2", label: "2 - Essential", description: "Short-term repair required" },
  { value: "3", label: "3 - Desirable", description: "Non-critical improvement" },
  { value: "4", label: "4 - Long-term", description: "Future lifecycle renewal" }
] as const;
