"use client";

import { useEffect, useMemo, useState } from "react";
import { MagnifyingGlass, Plus, Trash } from "@/components/ui/icons";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { authenticatedFetch } from "@/lib/client-api";

type Item = string | { id: string; name: string };
type ElementRow = { id: string; category: string; name: string; lifespan?: number; lifespanLabel?: string; lifecycle?: { id: string; typical_life_years: number; source_label: string }; construction: Item[]; defects: Item[] };
type Kind = "element" | "construction" | "defect" | "lifecycle";
const label = (item: Item) => typeof item === "string" ? item : item.name;

export function ReferenceData() {
  const [rows, setRows] = useState<ElementRow[]>([]); const [search, setSearch] = useState(""); const [kind, setKind] = useState<Kind>("element");
  const [name, setName] = useState(""); const [category, setCategory] = useState(""); const [elementId, setElementId] = useState(""); const [years, setYears] = useState(""); const [message, setMessage] = useState(""); const [loading, setLoading] = useState(true);
  const load = async () => { setLoading(true); const response = await authenticatedFetch("/api/reference-data"); const data = await response.json().catch(() => ({})); if (response.ok) setRows(data.elements ?? []); else setMessage(data.error ?? "Could not load reference data."); setLoading(false); };
  useEffect(() => { load(); }, []);
  const filtered = useMemo(() => rows.filter((row) => `${row.category} ${row.name} ${row.construction.map(label).join(" ")} ${row.defects.map(label).join(" ")}`.toLowerCase().includes(search.toLowerCase())), [rows, search]);
  const construction = filtered.flatMap((row) => row.construction.map((item) => ({ id: typeof item === "string" ? `${row.id}-construction-${item}` : item.id, element: row.name, name: label(item) })));
  const defects = filtered.flatMap((row) => row.defects.map((item) => ({ id: typeof item === "string" ? `${row.id}-defect-${item}` : item.id, element: row.name, name: label(item) })));
  async function add(event: React.FormEvent) { event.preventDefault(); setMessage(""); const response = await authenticatedFetch("/api/reference-data", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ kind, name: kind === "lifecycle" ? "Lifecycle" : name, category, elementId, years }) }); const data = await response.json().catch(() => ({})); if (!response.ok) { setMessage(data.error ?? "Could not save reference data."); return; } setName(""); setYears(""); setCategory(""); await load(); }
  async function remove(removeKind: Kind, id: string) { if (!confirm("Remove this reference-data record?")) return; const response = await authenticatedFetch(`/api/reference-data?kind=${removeKind}&id=${id}`, { method: "DELETE" }); if (!response.ok) { setMessage("Could not remove the record."); return; } await load(); }
  const table = (title: string, headings: string[], content: React.ReactNode) => <Card className="overflow-hidden p-0"><div className="border-b border-[var(--line)] px-5 py-4"><h2 className="font-display text-lg font-semibold">{title}</h2></div><div className="overflow-x-auto"><table className="w-full min-w-[560px] text-left text-sm"><thead className="bg-[var(--surface-muted)] text-xs font-semibold text-[var(--ink-muted)]"><tr>{headings.map((heading) => <th key={heading} className="px-5 py-3">{heading}</th>)}</tr></thead><tbody>{content}</tbody></table></div></Card>;
  return <div className="space-y-6"><Card className="p-5"><div className="flex flex-wrap items-end justify-between gap-4"><label className="relative min-w-[240px] flex-1"><span className="mb-2 block text-sm font-semibold">Find reference data</span><MagnifyingGlass className="absolute bottom-3 left-3 text-[var(--muted)]" size={18} /><input className="field pl-10" value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search elements and options" /></label><p className="max-w-sm text-sm text-[var(--ink-muted)]">Each data type is stored and managed in its own table. Changes apply to future surveys.</p></div></Card>
    <Card className="p-5"><form onSubmit={add} className="grid items-end gap-4 lg:grid-cols-[150px_minmax(0,1fr)_minmax(0,1fr)_auto]"><label className="grid gap-2 text-sm font-semibold">Data type<select className="field" value={kind} onChange={(event) => setKind(event.target.value as Kind)}><option value="element">Element</option><option value="construction">Construction type</option><option value="defect">Defect type</option><option value="lifecycle">Lifecycle reference</option></select></label>{kind === "element" ? <><label className="grid gap-2 text-sm font-semibold">Element name<input className="field" value={name} onChange={(event) => setName(event.target.value)} required /></label><label className="grid gap-2 text-sm font-semibold">Category<input className="field" value={category} onChange={(event) => setCategory(event.target.value)} placeholder="e.g. External Envelope" required /></label></> : <><label className="grid gap-2 text-sm font-semibold">Element<select className="field" value={elementId} onChange={(event) => setElementId(event.target.value)} required><option value="">Select element</option>{rows.map((row) => <option value={row.id} key={row.id}>{row.category} · {row.name}</option>)}</select></label>{kind === "lifecycle" ? <label className="grid gap-2 text-sm font-semibold">Typical life (years)<input className="field" type="number" min="1" value={years} onChange={(event) => setYears(event.target.value)} required /></label> : <label className="grid gap-2 text-sm font-semibold">Option name<input className="field" value={name} onChange={(event) => setName(event.target.value)} required /></label>}</>}<Button type="submit"><Plus size={17} />Add record</Button></form>{message ? <p className="mt-3 text-sm text-[var(--danger)]" role="alert">{message}</p> : null}</Card>
    {table("Elements", ["Category", "Element", "Typical life", ""], loading ? <tr><td className="px-5 py-5 text-[var(--ink-muted)]" colSpan={4}>Loading reference data…</td></tr> : filtered.map((row) => <tr className="border-t border-[var(--line)]" key={row.id}><td className="px-5 py-3 text-[var(--ink-muted)]">{row.category}</td><td className="px-5 py-3 font-semibold">{row.name}</td><td className="px-5 py-3">{row.lifecycle?.typical_life_years ?? row.lifespan ?? "—"}{row.lifecycle || row.lifespan ? " years" : ""}</td><td className="px-5 py-2 text-right">{!row.id.startsWith("demo-") && <Button size="sm" variant="ghost" onClick={() => remove("element", row.id)} aria-label={`Remove ${row.name}`}><Trash size={16} /></Button>}</td></tr>))}
    {table("Construction types", ["Element", "Construction type", ""], construction.length ? construction.map((item) => <tr className="border-t border-[var(--line)]" key={item.id}><td className="px-5 py-3 text-[var(--ink-muted)]">{item.element}</td><td className="px-5 py-3">{item.name}</td><td className="px-5 py-2 text-right">{!item.id.includes("-construction-") && <Button size="sm" variant="ghost" onClick={() => remove("construction", item.id)} aria-label={`Remove ${item.name}`}><Trash size={16} /></Button>}</td></tr>) : <tr><td className="px-5 py-5 text-[var(--ink-muted)]" colSpan={3}>No construction types match this search.</td></tr>)}
    {table("Defect types", ["Element", "Defect type", ""], defects.length ? defects.map((item) => <tr className="border-t border-[var(--line)]" key={item.id}><td className="px-5 py-3 text-[var(--ink-muted)]">{item.element}</td><td className="px-5 py-3">{item.name}</td><td className="px-5 py-2 text-right">{!item.id.includes("-defect-") && <Button size="sm" variant="ghost" onClick={() => remove("defect", item.id)} aria-label={`Remove ${item.name}`}><Trash size={16} /></Button>}</td></tr>) : <tr><td className="px-5 py-5 text-[var(--ink-muted)]" colSpan={3}>No defect types match this search.</td></tr>)}
    {table("Lifecycle references", ["Element", "Typical life", "Source"], filtered.map((row) => <tr className="border-t border-[var(--line)]" key={`${row.id}-life`}><td className="px-5 py-3 font-medium">{row.name}</td><td className="px-5 py-3">{row.lifecycle?.typical_life_years ?? row.lifespan ?? "—"}{row.lifecycle || row.lifespan ? " years" : ""}</td><td className="px-5 py-3 text-[var(--ink-muted)]">{row.lifecycle?.source_label ?? row.lifespanLabel ?? "Not recorded"}</td></tr>))}
  </div>;
}
