"use client";

import { Card } from "@/components/ui/card";
import { motion } from "framer-motion";

export function Skeleton({ className = "" }: { className?: string }) {
  return <motion.span aria-hidden className={`block rounded-lg bg-[var(--surface-muted)] ${className}`} initial={{ opacity: 0.45 }} animate={{ opacity: [0.45, 0.9, 0.45] }} transition={{ duration: 1.5, repeat: Infinity, ease: "easeInOut" }} />;
}

export function PageSkeleton({ variant = "dashboard" }: { variant?: "dashboard" | "table" | "workspace" | "detail" }) {
  if (variant === "table") return <div className="grid gap-6"><Skeleton className="h-10 w-64" /><Skeleton className="h-5 w-96 max-w-full" /><Card className="overflow-hidden p-0"><div className="grid gap-3 border-b border-[var(--line)] p-4 sm:grid-cols-4"><Skeleton className="h-11" /><Skeleton className="h-11" /><Skeleton className="h-11" /><Skeleton className="h-11" /></div><div className="grid gap-px bg-[var(--line)] p-px">{Array.from({ length: 8 }).map((_, index) => <div key={index} className="grid grid-cols-5 gap-4 bg-[var(--surface)] p-5"><Skeleton className="h-4" /><Skeleton className="h-4" /><Skeleton className="h-4" /><Skeleton className="h-4" /><Skeleton className="h-4" /></div>)}</div></Card></div>;
  if (variant === "workspace") return <div className="grid gap-7"><div className="flex items-center justify-between"><div className="grid gap-3"><Skeleton className="h-10 w-72" /><Skeleton className="h-5 w-[28rem] max-w-full" /></div><Skeleton className="h-11 w-48" /></div><div className="grid gap-4 xl:grid-cols-[1fr_340px]"><Card className="grid gap-5 p-6 sm:grid-cols-3"><Skeleton className="h-12" /><Skeleton className="h-12" /><Skeleton className="h-12" /></Card><Card className="grid gap-4 p-6"><Skeleton className="h-8 w-36" /><Skeleton className="h-3 w-full" /></Card></div><Skeleton className="h-7 w-56" /><div className="grid gap-5">{Array.from({ length: 5 }).map((_, index) => <Card key={index} className="overflow-hidden p-0"><div className="flex justify-between border-b border-[var(--line)] p-5"><Skeleton className="h-6 w-48" /><Skeleton className="h-9 w-28" /></div><div className="grid md:grid-cols-3">{Array.from({ length: 3 }).map((__, item) => <div key={item} className="grid gap-3 border-b border-[var(--line)] p-5"><Skeleton className="h-5 w-32" /><Skeleton className="h-6 w-24" /></div>)}</div></Card>)}</div></div>;
  if (variant === "detail") return <div className="grid gap-6"><Skeleton className="h-10 w-72" /><Skeleton className="h-5 w-[32rem] max-w-full" /><div className="grid gap-5 lg:grid-cols-[1fr_320px]"><Card className="grid gap-5 p-6"><Skeleton className="h-8 w-64" />{Array.from({ length: 6 }).map((_, index) => <Skeleton key={index} className="h-12 w-full" />)}</Card><Card className="grid gap-4 p-6"><Skeleton className="h-7 w-40" />{Array.from({ length: 5 }).map((_, index) => <Skeleton key={index} className="h-10 w-full" />)}</Card></div></div>;
  return <div className="grid gap-6"><div className="flex items-end justify-between"><div className="grid gap-3"><Skeleton className="h-10 w-80" /><Skeleton className="h-5 w-[34rem] max-w-full" /></div><Skeleton className="h-11 w-40" /></div><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5">{Array.from({ length: 5 }).map((_, index) => <Card key={index} className="grid gap-4 p-5"><Skeleton className="size-11 rounded-xl" /><Skeleton className="h-4 w-28" /><Skeleton className="h-9 w-20" /><Skeleton className="h-3 w-32" /></Card>)}</div><div className="grid gap-5 xl:grid-cols-3">{Array.from({ length: 6 }).map((_, index) => <Card key={index} className="grid gap-5 p-6"><Skeleton className="h-6 w-44" /><Skeleton className="h-4 w-64 max-w-full" />{Array.from({ length: 4 }).map((__, item) => <Skeleton key={item} className="h-8 w-full" />)}</Card>)}</div></div>;
}

export function LoadingLabel({ label = "Loading survey data" }: { label?: string }) {
  return <div className="flex items-center gap-3 text-sm text-[var(--ink-muted)]" role="status" aria-live="polite"><span className="size-2 animate-pulse rounded-full bg-[var(--brand)]" />{label}</div>;
}
